name: Export Docker Image from Docker Hub

on:
  push:
    branches:
      - main

jobs:
  export-docker-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

    - name: Pull Docker image
      run: docker pull tooljet/try:ee-lts-latest

    - name: Save Docker image to file
      run: docker save tooljet/try:ee-lts-latest -o ./docker-image.tar

    - name: Compress Docker image
      run: gzip -9 ./docker-image.tar

    - name: Upload Docker image artifact
      uses: actions/upload-artifact@cc9f3e25b927df46c3b95982ca25dd8d30184d9b
      with:
        name: docker-image
        path: ./docker-image.tar.gz
        retention-days: 5
